#-------------------------
# User
#-------------------------


# User : create
POST  http://localhost:3333/api/user/create HTTP/1.1
content-type: application/json

{
    "name":"e",
    "age":"11"
}

###
# User : read
GET    http://localhost:3333/api/user/read HTTP/1.1
content-type: application/json

###
# User : read id指定
GET    http://localhost:3333/api/user/read?id=4 HTTP/1.1
content-type: application/json


###
# User : update
POST  http://localhost:3333/api/user/update HTTP/1.1
content-type: application/json

{
    "id": "6",
    "name": "あいうえお",
    "age":"50"
}

###
# User : delete
GET    http://localhost:3333/api/user/delete?id=3 HTTP/1.1
content-type: application/json



#-------------------------
# Board
#-------------------------

###
# Board : create
POST  http://localhost:3333/api/board/create HTTP/1.1
content-type: application/json

{
    "title":"ああああああああ",
    "text":"いいいいいいいいいいいいい"
}

###
# Board : read
GET    http://localhost:3333/api/board/read HTTP/1.1
content-type: application/json

###
# Board : read id指定
GET    http://localhost:3333/api/board/read?id=25 HTTP/1.1
content-type: application/json

###
# Board : update
POST  http://localhost:3333/api/board/update HTTP/1.1
content-type: application/json

{
    "id":"14",
    "title":"asdf",
    "text":"eeeeeeeeeeee"
}

###
# Board : delete
GET    http://localhost:3333/api/board/delete?id=24 HTTP/1.1
content-type: application/json