#-------------------------
# User
#-------------------------
# Create
POST  http://localhost:3333/api/user/create HTTP/1.1
content-type: application/json

{
    "name":"e",
    "age":"11"
}

### Read
GET    http://localhost:3333/api/user/read HTTP/1.1
content-type: application/json

### Read id指定
GET    http://localhost:3333/api/user/read?id=3 HTTP/1.1
content-type: application/json

### Update
POST  http://localhost:3333/api/user/update HTTP/1.1
content-type: application/json

{
    "id": "6",
    "name": "あいうえお",
    "age":"50"
}

### Delete
GET    http://localhost:3333/api/user/delete?id=3 HTTP/1.1
content-type: application/json



#-------------------------
# Board
#-------------------------
### Create
POST  http://localhost:3333/api/board/create HTTP/1.1
content-type: application/json

{
    "title":"ああああああああ",
    "text":"いいいいいいいいいいいいい"
}

### Read
GET    http://localhost:3333/api/board/read HTTP/1.1
content-type: application/json

### Read id指定
GET    http://localhost:3333/api/board/read?id=25 HTTP/1.1
content-type: application/json

### Update
POST  http://localhost:3333/api/board/update HTTP/1.1
content-type: application/json

{
    "id":"14",
    "title":"asdf",
    "text":"eeeeeeeeeeee"
}

### Delete
GET    http://localhost:3333/api/board/delete?id=24 HTTP/1.1
content-type: application/json